### Numpy 연습문제
**필요한 모듈은 import 하여 사용합니다.**

---

In [23]:
# 이곳에 필요한 모듈 import 한 후 실행
import numpy as np
from load_utils import load_matrix,load_column,load_one_stock,load_dates,load_codes

1. 다음 리스트 [1, 2, 3, 4, 5]를 ndarray로 변환하고, 배열의 차원(ndim)과 형태(shape)을 출력하시오.

In [3]:
arr=np.array([1,2,3,4,5])
print(f"ndim:{np.ndim(arr)}")
print(f"shape:{np.shape(arr)}")

ndim:1
shape:(5,)


2. np.arange()를 이용해 0부터 20까지의 짝수로 이루어진 배열을 생성하시오.

In [6]:
arr=np.arange(0,21,2)
print(f"arr:{arr}")

arr:[ 0  2  4  6  8 10 12 14 16 18 20]


3. 다음 제시된 리스트를 배열로 변환한 후, 3 이상인 값만 추출하는 불리언 인덱싱 코드를 작성하시오.

In [8]:
list3 = [1,3,5,2,8,3]
arr = np.array(list3)
mask=arr>=3
print(f"3이상인 arr: {arr[mask]}")


3이상인 arr: [3 5 8 3]


4. 다음 제시된 리스트를 배열로 변환한 후, 두 번째 행만 슬라이싱하여 출력하시오.

In [10]:
list4 = [[10, 20, 30], [40, 50, 60], [70, 80, 90]]
arr=np.array(list4)
print(arr[1:2])

[[40 50 60]]


5. 다음 제시된 리스트를 배열로 변환한 후, 모든 홀수에만 10을 더하는 벡터화 연산을 수행하시오.

In [14]:
list5 = [1, 2, 3, 4, 5]
arr=np.array(list5)
arr1=np.where(arr%2!=0 ,arr+10,arr)
print(arr1)


[11  2 13  4 15]


6. 다음 제시된 실수 리스트를 배열로 변환한 후, 반올림한 정수형 배열로 변환하시오.\
   주의 : astype 만 쓰면 소수점 아래가 버려져서 값이 새어나간다.

    - [출력 예시]
        - np.array([52000.9, -3.7]) -> [52001, -4]

    - [힌트] 반올림을 먼저 하고 타입을 바꾼다. 순서가 중요하다.

In [21]:
list6 = [52000.9, 51999.2, -3.7, 52000.5]
arr=np.array(list6)
arr_round=np.round(arr,0)
arr_int=arr_round.astype("int64")
print(arr_int)

[52001 51999    -4 52000]


#### == 아래 문제들은 실습용 데이터(prices.csv, load_utils.py)를 활용하여 풀이해보세요. ==

7. 첫 종목의 종가 데이터를 기준으로 최저가, 최고가와 그에 해당하는 날짜를 각각 출력하시오. \
    (실습용 데이터의 prices 와 dates 는 길이와 순서가 같다.)

    - [출력 예시]
        - (25899, numpy.datetime64('2023-10-16'), 8885, numpy.datetime64('2026-05-21'))

    - [힌트] max 는 '값', argmax 는 '그 값이 있는 위치' 다.\
            위치를 얻으면 길이가 같은 다른 배열에서 같은 자리를 꺼낼 수 있다.

In [ ]:
dates=load_dates()
prices=load_one_stock()
codes=load_codes()
print(f"{codes[0]}의 종가")
print(f" 최저가 : {prices.min():,.0f}원 ({dates.min()})") # 이렇게하면 가장 과거날짜로 구함
print(f" 최고가 : {prices.max():,.0f}원 ({dates.max()})") # 이건 최근거
max_idx = prices.argmax()   # 가장 큰 값이 있는 위치
min_idx = prices.argmin()   # 가장 작은 값이 있는 위치
print(f"최저가 : {prices[min_idx]:,}원 ({dates[min_idx]})") #이렇게가 정석 
print(f"최고가 : {prices[max_idx]:,}원 ({dates[max_idx]})")




G0001의 종가
 최저가 : 8,885원 (2023-09-25)
 최고가 : 25,899원 (2026-09-07)
최저가 : 8,885원 (2026-05-21)
최고가 : 25,899원 (2023-10-16)


8. 종가 데이터를 기준으로 각 종목별 평균가와, 날짜별 평균가를 구하시오. 
    또한, 각 종목에서 자기 평균을 뺀 배열을 구하시오.
    
    [힌트]
    - 종목별 평균가 : (종목 수,) 배열 
    
    - 날짜별 평균가 : (날짜 수,) 배열
    
    - 각 종목에서 자기 평균을 뺀 배열 : (종목 수, 날짜 수) 배열 \
        결과의 종목별 평균은 0 이 되어야 한다.

In [ ]:
dates=load_dates()
prices=load_one_stock()
codes=load_codes()
matrix = load_matrix()   # (120, 750)
codes = load_codes()     # (120,)
print(f" 날짜별 평균 : {matrix.mean(axis=0)[:5]} {matrix.mean(axis=0).shape}")
print(f" 종목별 평균 : {matrix.mean(axis=1)[:5]} {matrix.mean(axis=1).shape}")

means=matrix.mean(axis=1,keepdims=True)
result=matrix-means
print(result.shape)




 전체 평균 : 46294.027022222224
 날짜별 평균 : [53454.25833333 52814.25       53074.13333333 53268.1
 52707.94166667] (750,)
 종목별 평균 : [15809.688      30689.94266667 14169.368      54451.92933333
 67169.48533333] (120,)
(120, 750)
